name: RegentParticleDSL tests

on:
    push:
        branches:
            - [master]
    pull_request:
        branches: [master]
    tags:
       - v*

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setp-python@v2
              with:
                  python-version: 3.8
            - name: Install Dependencies
              run: |
                  sudo apt update
                  sudo apt install -y build-essential clang-3.5 git libclang-3.5-dev libncurses5-dev llvm-3.5-dev wget zlib1g-dev libhdf5-dev cmake vim python3 python3-pip hdf5-tools
                  h5stat -V
                  h5cc --version
                  pip3 install --upgrade pip
                  pip3 install numpy h5py
                  git clone -b master https://github.com/StanfordLegion/legion.git
                  LLVM_CONFIG=llvm-config-3.5 python3 legion/language/install.py --rdir=auto --hdf5 -j --no-terra-cmake
            -name: Run examples
            run: |
                echo "Hello"


